In [76]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTest.csv
/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv
/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv
/kaggle/input/datasets/binib1997/superstore/Superstore.csv

In [212]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# import datasets on a dataframe

In [211]:
store = pd.read_csv('/kaggle/input/datasets/binib1997/superstore/Superstore.csv', encoding='latin-1')
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
iris = pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
climate = pd.read_csv('/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv')

# Series

# 1. Create a series from a list

In [54]:
l = [10,20,30,40,50]
p = pd.Series(l)
p

0    10
1    20
2    30
3    40
4    50
dtype: int64

# 2. Create series from a dictionary

In [55]:
d = {
    'A':10,
    'B':15,
    'C':20,
    'D':25,
    'E':30,
}

f = pd.Series(d)
f

A    10
B    15
C    20
D    25
E    30
dtype: int64

# 3. Create a series from dataframe

In [56]:
df = pd.DataFrame({
    'Name': ['Yasin', 'Rahim', 'Karim'],
    'Age': [22, 23, 21]
})

print(df)

    Name  Age
0  Yasin   22
1  Rahim   23
2  Karim   21

# 4. Apply below operations on a series to understand about a series

In [57]:
# head
# tail
# sample
# size
# dtype
# astype
# index
# values

In [58]:
s = pd.Series([10, 20, 30, 40, 50, 60, 70])
s.head(2)
s.tail(3)
s.sample()
s.size
s = s.astype(float)
s.dtype
s.index
s.values

array([10., 20., 30., 40., 50., 60., 70.])

# 5. Change data-type of a series

In [59]:
s = pd.Series([10, 20, 30, 40, 50, 60, 70])
s = s.astype(float)
s

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
5    60.0
6    70.0
dtype: float64

### 6. Apply below mathematical operations on a series

In [60]:
# count
# sum
# product
# min
# max
# mean
# median
# mode
# describe
# std
# var

In [61]:
s = pd.Series([10, 20, 30, 40, 50, 60, 70])
# s.count()
# s.sum()
# s.prod()
# s.min()
# s.max()
# s.mean()
# s.median()
# s.mode()
# s.describe()
# s.std()
# s.var()

# 7. Do 3 slicing operations on a series

In [62]:
s = pd.Series([10, 20, 30, 40, 50, 60, 70])
print(s[0:3])
print(s[::-1])
print(s[0:7:2])

0    10
1    20
2    30
dtype: int64
6    70
5    60
4    50
3    40
2    30
1    20
0    10
dtype: int64
0    10
2    30
4    50
6    70
dtype: int64

# Dataframe

# 1. Create a dataframe from a list

In [63]:
s = pd.Series([10, 20, 30, 70, 50, 60,70])
fr = pd.DataFrame(s,columns=['Number'])
fr['Name'] = ['Yasin','Kabul','Ramjan','Robin','Dabul','Abid','Yasir',]
fr

   Number    Name
0      10   Yasin
1      20   Kabul
2      30  Ramjan
3      70   Robin
4      50   Dabul
5      60    Abid
6      70   Yasir

# 2. Apply below dataframe understanding operations

In [64]:
# head
# tail
# sample
# info
# isnull
# duplicated

In [65]:
# fr.head(1)
#fr.tail(3)
#fr.sample()
#fr.info()
print(fr['Number'].duplicated())

0    False
1    False
2    False
3    False
4    False
5    False
6     True
Name: Number, dtype: bool

# 2. Apply below dataframe attribute operations

In [66]:
# shape
# dtypes
# columns
# values

In [67]:
#fr.shape
#fr['Number'].dtype
#fr['Name'].dtype
fr.columns
fr.values

array([[10, 'Yasin'],
       [20, 'Kabul'],
       [30, 'Ramjan'],
       [70, 'Robin'],
       [50, 'Dabul'],
       [60, 'Abid'],
       [70, 'Yasir']], dtype=object)

# 3. Apply below mathematical operations on a feature taken from dataframe

In [68]:
# count
# sum
# product
# min
# max
# mean
# median
# mode
# describe
# std
# var

In [69]:
# fr['Number'].count()
# fr['Number'].sum()
# fr['Number'].prod()
# fr['Number'].min()
# fr['Number'].max()
# fr['Number'].mode()
# fr['Number'].mean()
# fr['Number'].median()
# fr['Number'].std()
# fr['Number'].var()

# Selection and filtering

In [70]:
# loc
# iloc
# isin()
# logical operation (&, |, ~)

# 1. Select 11-20th rows and total_bill and tip columns from tips dataframe

In [71]:
# p = tips.iloc[11:21 , :2]
# p

# p = tips.loc[11:20,['total_bill','tip']]
# p

# 2. Select 0-20th rows and total_bill, tip and day columns from tips dataframe

In [84]:
# b = tips.loc[0:20,['total_bill','tip','day']]
# b

# p = tips.iloc[0:21 , [0,1,4]]
# p

3. Select customers who comes in sunday and total_bill is greater than 20 dollars

In [104]:
#tips.query("day == 'Sun' and total_bill > 20")
#tips.loc[(tips['day'] == 'Sun') & (tips['total_bill'] > 20)]

# 4. Select passengers who are male and age greater than 50 from titanic

In [106]:
#titanic.query("Sex=='male' and Age > 50")
#titanic.loc[(titanic['Sex'] == 'male') & (titanic['Age'] > 50)]

# 5. Select customers who are female and tip greater than 5 dollars from tips dataframe - write query operation

In [108]:
#tips.query("sex == 'Female' and tip > 5")

     total_bill   tip     sex smoker   day    time  size
52        34.81  5.20  Female     No   Sun  Dinner     4
85        34.83  5.17  Female     No  Thur   Lunch     4
155       29.85  5.14  Female     No   Sun  Dinner     5
214       28.17  6.50  Female    Yes   Sat  Dinner     3

# groupby

# 1. group on region based in store dataframe

In [114]:
t = store.groupby('Region')

# 2. Find region-wise average sales

In [116]:
t.Sales.mean()

Region
Central    215.772661
East       238.336110
South      241.803645
West       226.493233
Name: Sales, dtype: float64

# 3. Find region-wise average profit

In [117]:
t.Profit.mean()

Region
Central    17.092709
East       32.135808
South      28.857673
West       33.849032
Name: Profit, dtype: float64

# 4. Find region-wise maximum profit

In [118]:
t.Profit.max()

Region
Central    8399.9760
East       5039.9856
South      3177.4750
West       6719.9808
Name: Profit, dtype: float64

# 5. Apply multiple aggregate functions on region-wise sales

In [122]:
t.Sales.agg(['sum', 'min', 'max','var','mean'])

                 sum    min        max            var        mean
Region
Central  501239.8908  0.444  17499.950  400409.275802  215.772661
East     678781.2400  0.852  11199.968  385284.196615  238.336110
South    391721.9050  1.167  22638.480  600309.263888  241.803645
West     725457.8245  0.990  13999.960  275495.736259  226.493233

# 6. group on region and category wise

In [127]:
c = store.groupby(['Region','Category'])

# 7. Find region and category wise average sales

In [128]:
c.Sales.mean()

Region   Category
Central  Furniture          340.534644
         Office Supplies    117.458801
         Technology         405.753124
East     Furniture          346.574383
         Office Supplies    120.044425
         Technology         495.278469
South    Furniture          353.309289
         Office Supplies    126.282727
         Technology         507.753952
West     Furniture          357.302325
         Office Supplies    116.422377
         Technology         420.687533
Name: Sales, dtype: float64

# 8. Find region and category wise average, minimumm, maximum and sum sales

In [130]:
c.Sales.agg(['mean','min','max','sum'])

                               mean    min        max          sum
Region  Category
Central Furniture        340.534644  1.892   3504.900  163797.1638
        Office Supplies  117.458801  0.444   9892.740  167026.4150
        Technology       405.753124  1.980  17499.950  170416.3120
East    Furniture        346.574383  2.960   4416.174  208291.2040
        Office Supplies  120.044425  0.852   4663.736  205516.0550
        Technology       495.278469  2.970  11199.968  264973.9810
South   Furniture        353.309289  2.784   4297.644  117298.6840
        Office Supplies  126.282727  1.167   6354.950  125651.3130
        Technology       507.753952  1.584  22638.480  148771.9080
West    Furniture        357.302325  3.480   3610.848  252612.7435
        Office Supplies  116.422377  1.080   8187.650  220853.2490
        Technology       420.687533  0.990  13999.960  251991.8320

# Merging and joining

In [132]:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
    
    "name": ["Rahim", "Karim", "Hasan", "Sakib", "Nabil",
             "Tanvir", "Fahim", "Rafi", "Imran", "Shakil",
             "Arif", "Jahid", "Mehedi", "Siam", "Tareq",
             "Rakib", "Adnan", "Nayeem", "Foysal", "Rony"],
    
    "department": ["CSE", "EEE", "CSE", "BBA", "CSE",
                   "EEE", "CSE", "BBA", "CSE", "EEE",
                   "CSE", "BBA", "EEE", "CSE", "BBA",
                   "CSE", "EEE", "CSE", "BBA", "EEE"]
})

students

    student_id    name department
0          101   Rahim        CSE
1          102   Karim        EEE
2          103   Hasan        CSE
3          104   Sakib        BBA
4          105   Nabil        CSE
5          106  Tanvir        EEE
6          107   Fahim        CSE
7          108    Rafi        BBA
8          109   Imran        CSE
9          110  Shakil        EEE
10         111    Arif        CSE
11         112   Jahid        BBA
12         113  Mehedi        EEE
13         114    Siam        CSE
14         115   Tareq        BBA
15         116   Rakib        CSE
16         117   Adnan        EEE
17         118  Nayeem        CSE
18         119  Foysal        BBA
19         120    Rony        EEE

In [73]:
results = pd.DataFrame({
    "student_id": [101, 102, 103, 105, 106, 108, 109, 111, 112, 114,
                   121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
    "math": [85, 72, 91, 68, 77, 88, 74, 95, 81, 69,
             78, 84, 92, 73, 89, 67, 80, 94, 76, 83],
    "python": [90, 75, 88, 72, 80, 92, 79, 96, 85, 71,
               82, 87, 95, 76, 91, 70, 84, 93, 78, 86]
})

results

    student_id  math  python
0          101    85      90
1          102    72      75
2          103    91      88
3          105    68      72
4          106    77      80
5          108    88      92
6          109    74      79
7          111    95      96
8          112    81      85
9          114    69      71
10         121    78      82
11         122    84      87
12         123    92      95
13         124    73      76
14         125    89      91
15         126    67      70
16         127    80      84
17         128    94      93
18         129    76      78
19         130    83      86

In [74]:
departments = pd.DataFrame({
    "dept_id": [1, 2, 3, 4],
    "department": [
        "CSE",
        "EEE",
        "BBA",
        "Civil"
    ],
    "faculty": [
        "Engineering",
        "Engineering",
        "Business",
        "Engineering"
    ]
})

departments

   dept_id department      faculty
0        1        CSE  Engineering
1        2        EEE  Engineering
2        3        BBA     Business
3        4      Civil  Engineering

# 1. Create a dataframe contains students name,faculty and number on math and python

In [152]:
r = pd.merge(students,results, on = "student_id")
q = pd.merge(r,departments, on = 'department')
u = q.loc[: , ['name','faculty','math','python']]
u

     name      faculty  math  python
0   Rahim  Engineering    85      90
1   Karim  Engineering    72      75
2   Hasan  Engineering    91      88
3   Nabil  Engineering    68      72
4  Tanvir  Engineering    77      80
5    Rafi     Business    88      92
6   Imran  Engineering    74      79
7    Arif  Engineering    95      96
8   Jahid     Business    81      85
9    Siam  Engineering    69      71

# 2. Department wise students count

In [159]:
e = students.groupby('department').size().reset_index(name = 'S_count')
e

  department  S_count
0        BBA        5
1        CSE        9
2        EEE        6

# 3. Faculty wise department count

In [161]:
f = departments.groupby('faculty').size().reset_index(name = 'D_count')
f

       faculty  D_count
0     Business        1
1  Engineering        3

# 4. Find department wise highest number on each subject

In [173]:
r = pd.merge(students,results, on = "student_id", how = 'left')
q = pd.merge(r,departments, on = 'department',  how = 'left')
q
q.groupby('department').max()

            student_id    name  math  python  dept_id      faculty
department
BBA                119   Tareq  88.0    92.0        3     Business
CSE                118    Siam  95.0    96.0        1  Engineering
EEE                120  Tanvir  77.0    80.0        2  Engineering

# 5. Find faculty wise highest number on each subject

In [174]:
r = pd.merge(students,results, on = "student_id", how = 'left')
q = pd.merge(r,departments, on = 'department',  how = 'left')
q
q.groupby('faculty').max()

             student_id    name department  math  python  dept_id
faculty
Business            119   Tareq        BBA  88.0    92.0        3
Engineering         120  Tanvir        EEE  95.0    96.0        2

# Time-series

In [181]:
# use climate dataset
climate

date            datetime64[ns]
meantemp               float64
humidity               float64
wind_speed             float64
meanpressure           float64
dtype: object

# 1. convert time into datetime

In [179]:
climate['date'] = pd.to_datetime(climate['date'])
climate.dtypes

date            datetime64[ns]
meantemp               float64
humidity               float64
wind_speed             float64
meanpressure           float64
dtype: object

# 2. set date as index

In [192]:
climate.set_index('date')

             meantemp    humidity  wind_speed  meanpressure
date
2013-01-01  10.000000   84.500000    0.000000   1015.666667
2013-01-02   7.400000   92.000000    2.980000   1017.800000
2013-01-03   7.166667   87.000000    4.633333   1018.666667
2013-01-04   8.666667   71.333333    1.233333   1017.166667
2013-01-05   6.000000   86.833333    3.700000   1016.500000
...               ...         ...         ...           ...
2016-12-28  17.217391   68.043478    3.547826   1015.565217
2016-12-29  15.238095   87.857143    6.000000   1016.904762
2016-12-30  14.095238   89.666667    6.266667   1017.904762
2016-12-31  15.052632   87.000000    7.325000   1016.100000
2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 4 columns]

# 3. Select row of 13 january, 2015

In [193]:
#climate.loc['2015-01-13']

# 4. Select rows contains in april 2017

In [190]:
climate.loc['2017-04-01':'2017-04-30']

Empty DataFrame
Columns: [date, meantemp, humidity, wind_speed, meanpressure]
Index: []

# 5. Select rows from 11 september, 2014 to 25 september, 2014

In [186]:
climate.loc['2014-09-11':'2014-09-25']

Empty DataFrame
Columns: [date, meantemp, humidity, wind_speed, meanpressure]
Index: []

# 6. Calculate month-wise average windspeed

In [213]:
climate['date'] = pd.to_datetime(climate['date'])
climate.set_index('date', inplace=True)

climate.groupby(climate.index.month)['wind_speed'].mean()

date
1     4.945358
2     6.531042
3     7.696836
4     8.783093
5     9.022982
6     9.381606
7     7.418752
8     6.923782
9     7.596360
10    4.761333
11    3.872533
12    4.761964
Name: wind_speed, dtype: float64

# 7. Calculate month-wise highest meantemp

In [214]:
climate.groupby(climate.index.month)['meantemp'].max()

date
1     20.142857
2     23.875000
3     30.000000
4     35.687500
5     38.714286
6     38.500000
7     36.625000
8     34.125000
9     33.444444
10    33.269231
11    25.640000
12    25.000000
Name: meantemp, dtype: float64

# 8. Year-wise maximum, minimum and average humidity

In [215]:
climate.groupby(climate.index.year)['humidity'].agg(['max', 'min', 'mean'])

             max         min        mean
date
2013   94.000000   15.857143   63.046292
2014   96.857143   20.875000   59.767942
2015   98.000000   13.428571   61.430490
2016   94.300000   18.466667   58.740174
2017  100.000000  100.000000  100.000000

# 9. A new column contains previous 10 days average meantemp

In [219]:
g = climate['previous_10_days_avg'] = climate['meantemp'].rolling(10).mean().shift(1)
g

date
2013-01-01          NaN
2013-01-02          NaN
2013-01-03          NaN
2013-01-04          NaN
2013-01-05          NaN
                ...
2016-12-28    16.993723
2016-12-29    17.107129
2016-12-30    16.845224
2016-12-31    16.274748
2017-01-01    15.975011
Name: meantemp, Length: 1462, dtype: float64